### ISSUE TITLE
bug with program counter migration

### ISSUE THREAD

**Issue by YoungHS-NUS** [sbip-sg/solc-json-parser#23]
steps to reproduce the mismatch bug:
1. use file `./contracts/dev/1_Storage.sol`, compile with solc version 0.8.17
2. use remix ide, select solc version 0.8.17, compile it, publish on swarm, deploy on **Remix VM(London)**
3. Debug this contract then check opcode, we will see the difference shown in img

![image](https://user-images.githubusercontent.com/112539360/199666055-cbe5cb6f-c324-47f6-89a1-37d0951d9a04.png)

**Comment by cl2089** [comment]
Hi @YoungHS-NUS ,
- can you share the contract souce code? it's not in the repository 
- and which method you can calling?
- how to you print the left side? what's the meaning of the numbers on left side `20` and `21`, program counter I assume?

**Comment by cl2089** [comment]
You can compare wether the `SolidityAst.source_by_pc` is correct by 
1. Copy target contract to Remix, compile and deploy
2. Pick a method and execute it from Remix
3. Click **Debug** button for the completed transaction from the panel at bottom right of the Remix window 
4. Step through the program counter on the left side, you'll notice the source code highlighted on the right side in Remix. 
5. Copy the program counter here, compare the hightlighted source code with what you get from `ast.source_by_pc(CONTRACT_NAME, PC, False)`, the two should match

For example,

```bash
from solc_json_parser.parser import SolidityAst
ast = SolidityAst('./contracts/BlackScholesEstimate.sol', '0.5.17')
ast.source_by_pc('BlackScholesEstimate', 731, False)
```
should give you line 16-19, 
```
{'pc': 731,
 'fragment': 'while (c < b) {\n            b = c;\n            c = (x / c + c) / 2;\n        }',
 'begin': 461,
 'end': 538,
 'linenums': (16, 19),
 'source_path': './contracts/BlackScholesEstimate.sol'}
```
