### ISSUE TITLE
Bugs with contracts from SolidiFI benchmark.

### ISSUE THREAD

**Issue by minhhn2910** [sbip-sg/solc-json-parser#28]
This lib failed on contract: https://github.com/cl2089/SolidiFI-benchmark/blob/main/buggy_contracts/TOD/buggy_10.sol
```
Traceback (most recent call last):
  File "/solc-json-parser/solc_json_parser/parser.py", line 450, in compile
    out = solcx.compile_source(self.source, output_values=self.solc_compile_outputs, solc_version=self.exact_version)
   ...
solcx.exceptions.SolcError: An error occurred during execution
> command: `/home/minh/.solcx/solc-v0.4.21 --combined-json abi,bin,bin-runtime,srcmap,srcmap-runtime,asm,opcodes,ast -`
> return code: `1`
> stdout:

> stderr:
<stdin>:81:26: Error: Undeclared identifier.
        return keccak256(abi.encodePacked(_doc));
```
As the contract can be compiled with solc-0.4.22. It should be able to try and increase the solc version a few times before giving up.

**Comment by YoungHS-NUS** [comment]
I will take a look and improve on it

**Comment by YoungHS-NUS** [comment]
[https://github.com/cl2089/SolidiFI-benchmark/blob/main/buggy_contracts/TOD/buggy_10.sol](url)
This contract can not be compiled with solc-0.4.22 but can be compiled with 0.5.0
I have added support for automatically increasing versions. You can use this feature in the future by specifying the retry_num. The default is 0.
`ast = SolidityAst(f'{contracts_root}/dev/buggy_10.sol', retry_num=10)`

The code is pushed and under review now

**Comment by cl2089** [comment]
I don't think it's a good idea allow increasing the solc version here, we are already doing that in the caller (smart-fuzz) side. It will be too confusing to keep track of the versions.

**Comment by cl2089** [comment]
Solved in https://github.com/sbip-sg/solc-json-parser/pull/29
