### ISSUE TITLE
Bug with function raw data in abstract func/contract

### ISSUE THREAD

**Issue by minhhn2910** [sbip-sg/solc-json-parser#30]
https://github.com/cl2089/SolidiFI-benchmark/blob/b8f71552f8773bb8dd0104127a7eb082dd6b6200/buggy_contracts/Overflow-Underflow/buggy_20.sol#L152-L159

https://github.com/cl2089/SolidiFI-benchmark/blob/b8f71552f8773bb8dd0104127a7eb082dd6b6200/buggy_contracts/Overflow-Underflow/buggy_20.sol#L171-L178

`functions = ast.abstract_function_in_contract_by_name('RampInstantEscrowsPoolInterface')`

```
Function(raw='unction release(\n        address _pool,\n        address payable _receiver,\n        address _oracle,\n        bytes calldata _assetData,\n        bytes32 _paymentDetailsHash\n    )\n        external;\n', inherited_from='', abstract=True, visibility='external', signature='release(address, address payable, address, bytes, bytes32)', return_signature='()', name='release', modifiers=[], kind='function', state_mutability='nonpayable', line_num=(152, 160))
Function(raw='unction returnFunds(\n        address payable _pool,\n        address _receiver,\n        address _oracle,\n        bytes calldata _assetData,\n        bytes32 _paymentDetailsHash\n    )\n        external;\n', inherited_from='', abstract=True, visibility='external', signature='returnFunds(address payable, address, address, bytes, bytes32)', return_signature='()', name='returnFunds', modifiers=[], kind='function', state_mutability='nonpayable', line_num=(171, 179))

```

Somehow the first f is missing, raw starts with `unction` instead of `function` . Is this a bug of our library or in solc?

**Comment by YoungHS-NUS** [comment]
I know where is the problem now. In the comments `Copyright © 2017-2019 `, there is a special symbol ©. In utf-8, © takes two bytes(C2 A9), normal characters such as $ takes one bytes(24) and chinese character 你 takes three bytes(E4 BD A0). The solidity compiler doesn't understand utf-8  and thinks © is two different characters. I confirmed this findings by using a chinese character in comment, and the output will offset by 2(3-1) and with © the offset is by 1(2-1).

I am thinking how to handle this now, no conclusions yet.

**Comment by YoungHS-NUS** [comment]
bus is fixed
