### ISSUE TITLE
Parsing Contracts with importing from path "../" or with prefix

### ISSUE THREAD

**Issue by YoungHS-NUS** [sbip-sg/solc-json-parser#38]
When I was using SolcAST to build the evm signature database, I find out that we need to provide the remapping option and allow-path option to support compiling contracts with importing from path "../" or with prefix.

**Comment by cl2089** [comment]
You can use the script `solc_json_parser/fix_imports.py` to fix imports first. For example,

```
python solc_json_parser/fix_imports.py  --root folder_of_some_contracts/
```
