### ISSUE TITLE
Line mapping issue for a contract 

### ISSUE THREAD

**Issue by cl2089** [sbip-sg/solc-json-parser#46]
The program counter 7674 for the  contract [rubic.sol.txt](https://github.com/sbip-sg/solc-json-parser/files/10350366/rubic.sol.txt) compiled with solc version  `0.8.10` should point to the following line 

```
rubic.sol REENTRANCY CALL 7674
195         (bool success, ) = recipient.call{value: amount}("");
```

but now it's pointing to some other incorrect location. The bug exists starting from the commit https://github.com/sbip-sg/solc-json-parser/commit/ccdec5ae213b6c9c84c9ef164eea2638f30c085e It's  probably also a bug with unicode characters.

**Comment by YoungHS-NUS** [comment]
This issue is fixed by [PR 47](https://github.com/sbip-sg/solc-json-parser/pull/47)
